function retImageTimeArray = GetImageTimeArrayMatt(d)

    numImages = size(d, 1);
    imageTimeArray = zeros(numImages, 6);
    for q=1:numImages
        fileName = d(q).name;
        imageTimeArray(q,1:6) = [str2double(fileName(1:4)) ...
            str2double(fileName(6:7)) ...
            str2double(fileName(9:10)) ...
            str2double(fileName(13:14)) ...
            str2double(fileName(16:17)) ...
            str2double(fileName(19:20)) ...
            ];
    end

    retImageTimeArray = imageTimeArray;
end
